import DeanWilcoxsonTempImage from "../../../../Assets/Images/DeanWilcoxsonTempImage.jpg";
import BryanHuffstutlerTempImage from "../../../../Assets/Images/BryanHuffstutlerTempImage.jpg";

export const ContactData = {
  id:"contact",
  title: "Contacts",
  lightText: true,
  contacts: [
    {
      name: "Dean Wilcoxson",
      image: `${DeanWilcoxsonTempImage}`,
      qualifications: "Associates Degree in FullStack Web Development",
      languages: [
        "HTML,",
        "CSS,",
        "Python",
        "Styled-Components,",
        "Javascript,",
        "React,",
        "Express,",
        "MySQL,",
        "MongoDB,",
        "JSON,",
        "OOP,",
        "TDD,",
        "Node,",
        "REST Design,",
      ],
      phoneNumber: "(209) 840-0950",
      city: "Oakdale,",
      state: "CA",
      zipCode: "95361",
      yearsExp: "3 Years Experience",
    },
    {
      name: "Bryan Huffstutler",
      image: `${BryanHuffstutlerTempImage}`,
      qualifications: "Associates Degree in FullStack Web Development",
      languages: [
        "HTML,",
        "Javascript,",
        "Tailwind,",
        "Material-UI,",
        "Node,",
        "Typescript,",
        "React,",
        "Next,",
        "Python",
        "Express.JS,",
        "MySQL,",
        "MongoDB,",
        "JSON,",
        "OOP,",
        "TDD,",
        "CSS,",
        "REST Design,",
      ],
      phoneNumber: "(217) 320-9505",
      city: "Staunton,",
      state: "IL",
      zipCode: "62088",
      yearsExp: "5 Years Experience",
    },
  ],
};
