// import {} from '../../../../Assets/Images/'
// import {} from '../../../../Assets/Images/'

export const ContactData = [
  {
    name: "Dean Wilcoxson",
    // image:`${}`,
    qualifications: "Associates Degree in FullStack",
    languages: [
      "HTML5",
      "CSS3",
      "Javascript",
      "Python",
      "React.JS",
      "Express.JS",
      "Node.JS",
      "Styled-Components",
      "MySQL",
      "MongoDB",
      "JSON",
      "RESTful API Design",
    ],
    phoneNumber: "Phone Number: 209-840-0950",
    city: "City: Oakdale",
    state: "State: California",
    zipCode: "Zip Code: 95361",
    yearsExp: "Years of Experience: 3",
  },
  {
    name: "Bryan Huffstutler",
    // image:`${}`,
    qualifications: "Associates Degree in FullStack",
    languages: [
      "HTML5",
      "CSS3",
      "Javascript",
      "Python",
      "React.JS",
      "Express.JS",
      "Node.JS",
      "MySQL",
      "MongoDB",
      "JSON",
      "Tailwind.CSS",
      "Typescript",
      "Material-UI",
      "RESTful API Design",
    ],
    phoneNumber: "Phone Number: 217-320-9505",
    city: "City: Staunton",
    state: "State: Illinois",
    zipCode: "Zip Code: 62088",
    yearsExp: "Years of Experience: 5",
  },
];
